// Rebuild the bundled character bank without touching science or pet data.
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const cards = JSON.parse(fs.readFileSync(path.join(root, 'data/hanzi-1000.json'), 'utf8'));
if (cards.length !== 1000 || new Set(cards.map(c => c.c)).size !== 1000) {
  throw new Error('The Taiwan elementary bank must contain exactly 1,000 unique characters.');
}
const sizes = [200, 200, 150, 150, 150, 150];
const bank = {};
let offset = 0;
for (let level = 1; level <= 6; level++) {
  const levelCards = cards.slice(offset, offset + sizes[level - 1]);
  bank[level] = [];
  for (let i = 0; i < levelCards.length; i += 20) {
    const batch = levelCards.slice(i, i + 20);
    const start = offset + i + 1, end = start + batch.length - 1;
    bank[level].push({
      f: `常用字 ${String(start).padStart(3, '0')}–${String(end).padStart(3, '0')}`,
      fe: `Everyday characters ${start}–${end}`,
      rule: '先讀例詞，認識這個詞裡的讀音與意思，再練習選字和查部首。同一個字在其他詞中可能有不同讀音。',
      re: 'Read each example word, learn its pronunciation and meaning, then practice characters and dictionary radicals. A character may have other readings in other words.',
      chars: batch,
    });
  }
  offset += sizes[level - 1];
}
const meta = {
  id: 'tw-primary-1000-v1', name: '台灣小學常用一千字', count: 1000,
  source: '教育部《國小學童常用字詞調查報告書》（2002 年二版）字頻總表',
  sourceUrl: 'https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/PRIMARY/shrest2-1.htm',
  selection: '依字頻順序選取，將裏統一為裡、台統一為臺並去重，取前 1,000 字。',
  levelNote: 'L1–L6 是常見程度的練習批次，不代表學校年級，也不是官方指定的一千字名單。',
  dictionary: '教育部《國語辭典簡編本》2026-06-26 公眾授權資料；少數例詞為本專案編寫。',
};
const target = path.join(root, 'js/data.js');
const original = fs.readFileSync(target, 'utf8');
const marker = '/* ── 自然:概念卡 + 推理式題目 ── */';
const index = original.indexOf(marker);
if (index < 0) throw new Error('Science boundary not found');
const header = `const CONTENT_VERSION='v23 · 2026-09-14 · 台灣小學常用一千字';\n\n` +
  `// Generated by scripts/build-hanzi.cjs from data/hanzi-1000.json.\n` +
  `// Source and attribution: docs/HANZI_SOURCES.md.\n` +
  `const HANZI_META = ${JSON.stringify(meta, null, 2)};\n\n` +
  `const HANZI = ${JSON.stringify(bank, null, 2)};\n\n`;
fs.writeFileSync(target, header + original.slice(index));
console.log(`Built ${cards.length} characters in ${Object.values(bank).flat().length} practice packs.`);
